apiVersion: v1
kind: Service
namespace: plangeneratorflink-namespace
metadata:
  name: kafka
spec:
#  type: NodePort
  ports:
    - name: "9092"
      port: 9092
    - name: "9093"
      port: 9093
  selector:
    pgf.kafka: 'yes'
