apiVersion: v1
kind: Service
namespace: plangeneratorflink-namespace
metadata:
  labels:
    pgf.zookeeper: 'yes'
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    pgf.zookeeper: 'yes'
