- hosts: masters
  become: yes
  tasks:
    - name: install openjdk, pip, htop
      apt:
        name: 
         - openjdk-11-jdk
         - python3-pip
         - htop
        update_cache: yes

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: "{{ username }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/users/{{ username }}/.kube/config"
        remote_src: yes
        owner: "{{ username }}"

    - name: install Pod network
      become: yes
      become_user: "{{ username }}"
      shell: kubectl create -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: $HOME

    - name: Install bottle python package
      become: yes
      pip:
        name: kubernetes
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: "{{ username }}"
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Print join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="kubernetes_join_command" mode=0777
