- hosts: workers
  become: yes
  gather_facts: yes
  tasks:
   - name: Copy join command from local machine to all worker nodes
     become: yes
     copy:
       src: "kubernetes_join_command"
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the worker nodes to the k8s cluster
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not
