apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.js: |
    const rootUser = cat('/etc/k8s/admin/MONGO_ROOT_USERNAME');
    const rootPass = cat('/etc/k8s/admin/MONGO_ROOT_PASSWORD');
    const mongoUser = cat('/etc/k8s/MONGO_USERNAME');
    const mongoPassword = cat('/etc/k8s/MONGO_PASSWORD');

    const adminDb = db.getSiblingDB('admin');
    adminDb.auth(rootUser, rootPass);
    print('Successfully authenticated admin user');

    const pgfDB = db.getSiblingDB('plangeneratorflink');
    pgfDB.createUser(
            {
                user: mongoUser,
                pwd: mongoPassword,
                roles: [
                    {
                        role: "readWrite",
                        db: "plangeneratorflink"
                    }
                ]
            }
    );
