apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-port
  selector:
    app: database
